### PR TITLE
New svg set for Arched historical buildings

### PR DESCRIPTION
**Pull request by enricofer**
It's designed modifying residential-left.svg and residential-right.svg,
following the illustrations guidelines and
keeping the the same proportions for basement, floor and roof
Is it acceptable for app improvement?

### CODE REVIEW

**Comment by louh** [comment]
@enricofer this is a really great start! thank you. We're reviewing this now and should have some comments for you soon.

**Comment by louh** [comment]
@enricofer here are our thoughts!

#### Recommendations
- Remove strokes on all shapes (e.g. trim pieces)
- Colors: provide an alternate color scheme for the right side building (similar to how the wide/narrow buildings have different color schemes now)
- Window surfaces
    - Add diagonal window pattern to all ground floor windows
    - (Right building) flip direction of window pattern to go from lower-left to upper-right
    - All window patterns need to have 45-degree lines (do not squash the shapes to fit window)
    - Revise & shift the pattern location of upper floor windows so that the lightest band does not cross directly in the middle of the window
- Window frames: Ensure that all frame pieces and muntins have the same width
- Window shutters: Use [the greens from our color palette](https://streetmix.readthedocs.io/en/latest/contributing/illustrations/#greens)
- Ground floor window: remove the inner shadow on the top and right side
- Ground floor shadow: make the shadow much lighter. We should use the same color (or degree of tint) that's used in the left wider building, in the shadow underneath the awning:
Screenshot 2020-01-25 11 35 26
   - Please note that the shadow is not applied to every element, like the window or its window trim.

Please let me know if you have any questions! Thanks again.

**Comment by louh** [comment]
Hi @enricofer, just wanted to see if you have any thoughts about the comments, above!

We can also take care of making those modifications for you, if you're okay with that?

**Comment by enricofer** [comment]
Hi @louh my project here don't start and don't even know when it will, so I turned my attention to other activities. Anyway, I'm happy to ear your interest I would work on that in few days editing the PR as you thought.
But feel free to go on straight now if you need...

**Comment by louh** [comment]
Hi @enricofer, if you're able to respond to the comments, please go ahead! I'm looking forward to incorporating your proposal, so let me know if / when you're able to update. Thanks!

**Comment by enricofer** [comment]
Hi @louh,
I made some edits to fulfil guidelines, even if, I must confess, I'm not so comfortable with vector graphics and inkskape.
Anyway I'm pretty happy with results except for the right color set that I find too pale.
Feel free to put your hands on it if you see further possible improvements.

**Comment by louh** [comment]
This is such a great improvement, thank you @enricofer! We'll review this, make tweaks as necessary, and get this in the pipeline for inclusion. Thanks again so much, I hope people can make great use of this soon.

**Comment by louh** [comment]
Hey @enricofer, we've made some updates and will merge your changes, with our changes on top. Any other comments before we put this in the pipeline for inclusion into Streetmix? Thanks again for your awesome contribution!

arched-historical-left
arched-historical-right

**Comment by enricofer** [comment]
You can go on for me.
Happy to partecipate!

**Pull request merged**
